### ISSUE TITLE
Error Trying to Download Image (from Minio)

### ISSUE THREAD

**Issue by dvnicolasdh** [qld-gov-au/ckanext-s3filestore#62] opened 2021-12-03 08:45 UTC
Hello, 

Successfully uploaded a small DATASET containing one image (14KB) through (a compiled) CKAN (v 2.9.4) to Minio (.exe version RELEASE.2021-11-24T23-19-33Z) using (compiled-develop) s3filestore (qld-gov-au/ckanext-s3filestore tag: 0.7.3).

**But** attempting to download the image file from Minio via CKAN using s3filestore doesn't work, and ckan complains (in the console) about: bytes-like object being read as "str".... (running under Python 3.6.8)

`2021-12-03 03:10:00,850 ERROR [ckan.config.middleware.flask_app] a bytes-like object is required, not 'str'`
`Traceback (most recent call last):`
> `  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request`
>> `    rv = self.dispatch_request()`

> `  File "/usr/lib/ckan/default/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request`
>> `    return self.view_functions[rule.endpoint](**req.view_args)`

> `  File "/usr/lib/ckan/default/src/ckanext-s3filestore/ckanext/s3filestore/views/resource.py", line 69, in resource_download`
>> `    url = upload.get_signed_url_to_key(key_path)`

> `  File "/usr/lib/ckan/default/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 277, in get_signed_url_to_key`
>> `    if cache_url and is_public_read != _is_presigned_url(cache_url):`

> `  File "/usr/lib/ckan/default/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 97, in _is_presigned_url`
>> `    parts = url.split('?')`

`TypeError: a bytes-like object is required, not 'str'`
`2021-12-03 03:10:00,923 INFO  [ckan.config.middleware.flask_app]  500 /dataset/a75dbe92-1c80-4d44-82bb-212c5beebd56/resource/1c4e3745-b308-4f40-b1a6-b3ce01f453aa/download/MYIMAGE.png render time 0.245 seconds`

Do others get the same behavior ?

**Comment by aruneko** [comment] 2021-12-06 09:06
I'm facing same error with minio.

**Comment by duttonw** [comment] 2021-12-06 22:44
Hi @aruneko  @dvnicolasdh,

We at Qld Gov are still trying to get all of the ckan plugins ([18 in total](https://github.com/qld-gov-au/ckan-qld-infrastructure/blob/master/vars/shared-OpenData.var.yml)) in our application to be 2.9 compatible, we still have many more to go before we can transition over to 2.9 in production.

Looking at the stack trace the issue is on https://github.com/qld-gov-au/ckanext-s3filestore/blob/master/ckanext/s3filestore/uploader.py#L97 

It seems it is not a String and we may be able to resolve it be running it through 'six' to ensure it is.
```
if not isinstance(text, six.text_type):
        text = six.text_type(text, 'utf-8')
```

@ThrawnCA  are you able to take a quick look and see if 2.9 could be passing something else instead? And if this would mitigate the issue that has been raised?

**Comment by ThrawnCA** [comment] 2021-12-07 00:09
The URL that we're trying to split is being retrieved from Redis cache, and I suspect we're getting a `bytes` object as a result. Probably the simplest fix is to apply `six.text_type` at line 275, when we're first populating "cache_url".

**Comment by duttonw** [comment] 2021-12-07 03:04
Hi @aruneko , @dvnicolasdh ,

Please try again, it should now be fixed on our develop branch.

**Comment by aruneko** [comment] 2021-12-08 09:55
hmm, I'm facing another error on the latest develop branch. It seems to be caused by `bytes` cache......

```
2021-12-08 09:48:18,176 DEBUG [ckanext.s3filestore.uploader] Checking that S3 object resources/1d17c6ae-aeb3-4095-b611-d2cb97a131ee/stops.txt exists
2021-12-08 09:48:18,200 DEBUG [ckanext.s3filestore.uploader] Returning cached URL for path resources/1d17c6ae-aeb3-4095-b611-d2cb97a131ee/stops.txt
2021-12-08 09:48:18,201 ERROR [ckan.config.middleware.flask_app] Could not build url for endpoint "b'http://minio:9000/ckan/resources/1d17c6ae-aeb3-4095-b611-d2cb97a131ee/stops.txt?response-content-disposition=attachment%3B%20filename%3Dstops.txt&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20211208%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211208T094741Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=67487d93a989c72f61b179095fb985a014ba120d40bd31f9eca3f58b34fe9335'". Did you mean 'resource.views' instead?
Traceback (most recent call last):
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ckan/.local/lib/python3.8/site-packages/ckanext/s3filestore/views/resource.py", line 70, in resource_download
    return redirect(url)
  File "/home/ckan/.local/lib/python3.8/site-packages/ckan/lib/helpers.py", line 215, in redirect_to
    _url = url_for(*uargs, **kw)
  File "/home/ckan/.local/lib/python3.8/site-packages/ckan/lib/helpers.py", line 353, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/home/ckan/.local/lib/python3.8/site-packages/ckan/lib/helpers.py", line 415, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ckan/.local/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/ckan/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint "b'http://minio:9000/ckan/resources/1d17c6ae-aeb3-4095-b611-d2cb97a131ee/stops.txt?response-content-disposition=attachment%3B%20filename%3Dstops.txt&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20211208%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211208T094741Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=67487d93a989c72f61b179095fb985a014ba120d40bd31f9eca3f58b34fe9335'". Did you mean 'resource.views' instead?
2021-12-08 09:48:18,286 INFO  [ckan.config.middleware.flask_app]  500 /dataset/139bc157-aad4-41d1-bcdf-68536734a642/resource/1d17c6ae-aeb3-4095-b611-d2cb97a131ee/download/stops.txt render time 0.196 seconds
```

**Comment by aruneko** [comment] 2021-12-08 10:01
The first time of downloading the file from the generated url has been succeeded. But after second times, the error has occured. That's why I think it comes from cached URL.

**Comment by duttonw** [comment] 2021-12-09 04:21
Hi @aruneko ,

Did you have latest [develop](https://github.com/qld-gov-au/ckanext-s3filestore/commit/19591f31f4edf1935c450344dcaa6785ffd9ffd1) as we updated the cache to run the string from redis through six string converted. 
i.e
https://github.com/qld-gov-au/ckanext-s3filestore/blob/develop/ckanext/s3filestore/views/resource.py#L69
goes to  def get_signed_url_to_key(self, key, extra_params={}):
https://github.com/qld-gov-au/ckanext-s3filestore/blob/19591f31f4edf1935c450344dcaa6785ffd9ffd1/ckanext/s3filestore/uploader.py#L260
which calls cache_url = self._cache_get(key)
https://github.com/qld-gov-au/ckanext-s3filestore/blob/19591f31f4edf1935c450344dcaa6785ffd9ffd1/ckanext/s3filestore/uploader.py#L130
that calls
https://six.readthedocs.io/#six.text_type

if it is the correct file, then i wonder if https://six.readthedocs.io/#six.ensure_text will fix it.

Regards

@duttonw

**Comment by aruneko** [comment] 2021-12-09 04:44
Thanks for your quick response.

Yes, certainly I use the latest develop branch. I've found the line which you point.

And when I tried to use `six.ensure_text` at line 130 in uploader.py, I have succeeded to download the file!

**Comment by ThrawnCA** [comment] 2021-12-09 05:25
Ah, https://newbedev.com/pythonic-way-to-ensure-unicode-in-python-2-and-3 has more context. Apparently calling `six.text_type` on a `bytes` object has counterintuitive results.

**Comment by duttonw** [comment] 2021-12-09 06:20
ok, this should be fixed now, also had to do a check to ensure the six module has the function, else leave it be.
https://github.com/qld-gov-au/ckanext-s3filestore/commit/ce0d49df4406e669f6441f21c3874f4fbcc3a8f0

**Closed** 2021-12-20 00:36 UTC
